# Generated by Django 3.2.9 on 2021-11-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20211115_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
