# Generated by Django 3.2.9 on 2021-11-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20211120_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
