# Generated by Django 3.2.9 on 2021-11-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_rename_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
