# Generated by Django 3.2.9 on 2021-11-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_auto_20211121_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
