# Generated by Django 3.2.9 on 2021-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_auto_20211121_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
    ]
