# Generated by Django 3.2.9 on 2021-11-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_remove_comment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
